# Numpy Arrays #
Then we doing python we had the data structure list and NumPy is famous for arrays. 

| Feature            | Python List          | NumPy Array              |
|-------------------|--------------------|--------------------------|
| Datatypes         | Mixed allowed       | Same data type only      |
| Performance       | Slower              | Much faster (C-level)    |
| Memory efficiency | Low                 | High                     |
| Vector operations | Manual loops        | Easy + Fast              |

In [1]:
import numpy as np

### *1. Basic Array Creation* ###

In [2]:
# Array
arr = np.array([1, 2, 3, 4, 5])
arr

array([1, 2, 3, 4, 5])

In [3]:
# list
list = [1, 2, 3, 4, 5.5,"Hello"]
list
# list can store different types of data, it does not convert the elements to same type.

[1, 2, 3, 4, 5.5, 'Hello']

In [4]:
list1 = [1, 2, 3, 4, 5.5]
list1

[1, 2, 3, 4, 5.5]

In [5]:
# list to array
np.array(list)
# as array can only store same type of data, it converts all the elements to string type.

array(['1', '2', '3', '4', '5.5', 'Hello'], dtype='<U32')

In [6]:
np.array(list1)
# it converts all the elememts to float type, as it is the highest type in the list.

array([1. , 2. , 3. , 4. , 5.5])

1. Vectors are 1D arrays
2. Matrices are 2D arrays
3. Tensors are 3D arrays or higher dimensional arrays


In [7]:
# Vectors
# one dimensional array is called vector. It can be row vector or column vector.
# Row vector
row_vector = np.array([[1, 2, 3, 4, 5]])
row_vector
# Column vector
column_vector = np.array([[1], [2], [3], [4], [5]])
column_vector


array([[1],
       [2],
       [3],
       [4],
       [5]])

In [8]:
# Matrix
# two dimensional array is called matrix. It can be row matrix or column matrix.
# Row matrix
row_matrix = np.array([[1, 2, 3], [4, 5, 6]])
row_matrix
# Column matrix
column_matrix = np.array([[1, 4], [2, 5], [3, 6]])
column_matrix


array([[1, 4],
       [2, 5],
       [3, 6]])

### *2. Array generation function* ###

In [ ]:
arr = np.arange(1, 11, 2) # (start, stop, step)
arr

array([1, 3, 5, 7, 9])

In [ ]:
arr = np.zeros((3,4)) # (rows, columns)
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
arr = np.ones((3,4)) # (rows, columns)
arr

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
arr = np.linspace(0, 10, 5) # (start, stop, number of elements)
arr

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

### *3. Random Generation Function* ###

In [19]:
# concept of normalization, it is used to generate random numbers between 0 and 1, it is used in machine learning to normalize the data.
arr = np.random.rand(3,4) # (rows, columns) 
arr 

array([[0.44444712, 0.4266763 , 0.29264772, 0.41407698],
       [0.93509586, 0.99102839, 0.79589197, 0.5085474 ],
       [0.44062243, 0.43086523, 0.11297506, 0.05163507]])

In [33]:
# concept of standardization, it is used to generate random numbers from normal distribution, it is used in machine learning to standardize the data.
arr = np.random.randn(3,4) # (rows, columns) # random number between -3 and 3
arr

array([[-0.39256667, -0.24018003, -0.15814985,  1.39940802],
       [ 0.44516996,  0.74901311, -2.6183285 ,  1.4963956 ],
       [ 0.35983033,  0.00320907,  0.5695738 , -0.11935328]])

In [ ]:
arr = np.random.randint(0, 6, (3, 4)) # (start, stop, size)
arr

array([[1, 2, 5, 5],
       [0, 2, 1, 0],
       [0, 5, 3, 2]], dtype=int32)

### *4. Array Attributes* ###

In [37]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [38]:
arr.shape

(3, 3)

In [39]:
arr.size

9

In [40]:
arr.dtype

dtype('int64')

### *5. Array Methods* ###

In [41]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
arr.min()  # minimum value in the array

np.int64(1)

In [ ]:
arr.max()  # maximum value in the array

np.int64(9)

In [ ]:
arr.sum()  # sum of all the elements in the array

np.int64(45)

In [ ]:
np.sum(arr,axis=0)    # sum of all the elements in the array along the columns (axis=0)

array([12, 15, 18])

In [ ]:
np.sum(arr,axis=1)   # sum of all the elements in the array along the rows (axis=1)

array([ 6, 15, 24])

In [ ]:
arr.mean()  # mean of all the elements in the array

np.float64(5.0)

In [ ]:
arr.std()   # standard deviation of all the elements in the array

np.float64(2.581988897471611)

In [ ]:
arr.argmax() # index of the max element

np.int64(8)

In [ ]:
arr.argmin() # index of the min element

np.int64(0)

### *6. Reshaping and Resizing* ###

In [52]:
arr = np.arange(1,31)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [54]:
arr = arr.reshape(6,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])