# Array Indexing #

In [1]:
import numpy as np

### 1. Numpy indexing and slicing of vectors ###

In [2]:
arr = np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [3]:
arr[6]  # indexing

np.int64(17)

In [4]:
arr[1:5]  # slicing

array([12, 13, 14, 15])

In [5]:
arr[1:5:2]  # slicing with step

array([12, 14])

In [6]:
arr[:6]  # Print index 0 to 5

array([11, 12, 13, 14, 15, 16])

In [7]:
arr[3:]  # print index 3 to n

array([14, 15, 16, 17, 18, 19, 20])

In [8]:
arr_slice = arr[:]  # print 0 to n
arr_slice

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [9]:
arr_slice = arr[::]
arr_slice

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [10]:
arr_slice = arr[3::2]
arr_slice

array([14, 16, 18, 20])

### 2. Numpy indexing and slicing of matrix ###

In [ ]:
arr = np.arange(1,31).reshape(6,5)
arr  

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [ ]:
arr[1]  # print row

array([ 6,  7,  8,  9, 10])

In [ ]:
arr[3,2]     # indexing

np.int64(18)

In [ ]:
slice = arr[0:2,1:3]    #slicing
slice

array([[2, 3],
       [7, 8]])

In [16]:
slice1 = arr[3:,3:]  # slicing
slice1

array([[19, 20],
       [24, 25],
       [29, 30]])

In [ ]:
arr[:,2]  #print column

array([ 3,  8, 13, 18, 23, 28])

### 3. Boolean indexing ###

In [18]:
arr = np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [20]:
bool_index = arr%2==0 
bool_index

array([False,  True, False,  True, False,  True, False,  True, False,
        True])

In [21]:
arr = arr[bool_index]
arr

array([12, 14, 16, 18, 20])