# ARRAY OPERATIONS #

In [1]:
import numpy as np

### 1. Arithmetic Operations ###

In [2]:
a = np.arange(1,6)
b = np.arange(6,11)
arr = np.arange(1,26).reshape(5,5)
arr1 = np.arange(11,36).reshape(5,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [3]:
arr1

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35]])

In [4]:
sum = a+b
sum

array([ 7,  9, 11, 13, 15])

In [5]:
c = arr1+arr
c

array([[12, 14, 16, 18, 20],
       [22, 24, 26, 28, 30],
       [32, 34, 36, 38, 40],
       [42, 44, 46, 48, 50],
       [52, 54, 56, 58, 60]])

In [6]:
c = a-b
c

array([-5, -5, -5, -5, -5])

In [7]:
c = a*b
c

array([ 6, 14, 24, 36, 50])

In [8]:
c = arr1*arr 
c

array([[ 11,  24,  39,  56,  75],
       [ 96, 119, 144, 171, 200],
       [231, 264, 299, 336, 375],
       [416, 459, 504, 551, 600],
       [651, 704, 759, 816, 875]])

In [9]:
c = a/b
c

array([0.16666667, 0.28571429, 0.375     , 0.44444444, 0.5       ])

In [10]:
c = a//b
c

array([0, 0, 0, 0, 0])

In [11]:
c = b**a
c

array([     6,     49,    512,   6561, 100000])

### 2. Broadcasting ###

In [12]:
l = [10,20,30,40,50]
arr = np.array(l)

In [13]:
d = arr+10
d

array([20, 30, 40, 50, 60])

In [14]:
d = arr-10 
d

array([ 0, 10, 20, 30, 40])

In [15]:
d = arr*10
d

array([100, 200, 300, 400, 500])

In [16]:
d = arr**2
d

array([ 100,  400,  900, 1600, 2500])

In [17]:
d = arr/15
d

array([0.66666667, 1.33333333, 2.        , 2.66666667, 3.33333333])

In [18]:
d = arr//15
d

array([0, 1, 2, 2, 3])

In [19]:
arr1 = np.arange(1,21).reshape(4,5)
arr1

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [20]:
arr1 + 10

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

### 3. Deep and Shallow Copy ###

In [21]:
a = np.arange(1,21)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [22]:
slice = a[:5]
slice = slice*10  # it is a shallow copy, the original array is affected by changes to the slice.
# The original array is modified after changing the slice, demonstrating that it is a shallow copy.

In [23]:
a[:2]*10
a        # in deep copy, the original array is not affected by changes to the slice.
# The original array remains unchanged after modifying the slice, demonstrating that it is a deep copy.

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [24]:
b = a 
b[0] = 100
a  # in assignment, the original array is affected by changes to the new variable, demonstrating that it is a shallow copy.

array([100,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20])

### 4. Matrix Operations ###

In [25]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])

In [26]:
matrix_multiplication = a @ b  # matrix miltiplication
matrix_multiplication

array([[19, 22],
       [43, 50]])

In [27]:
np.dot(a,b)  # another way to do matrix multiplication

array([[19, 22],
       [43, 50]])

In [28]:
a

array([[1, 2],
       [3, 4]])

In [29]:
a.T # transpose of a matrix

array([[1, 3],
       [2, 4]])

### 5. Advance Array Manipulation ###

#####  *Stacking Array* #####

In [30]:
# we cannot stack two matrixs or we stack two vectors only
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])

In [31]:
np.vstack((a,b))  # vertical stacking of arrays
# vertical stack is used to stack arrays vertically (row-wise).

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [32]:
np.hstack((a,b))  # horizontal stacking of arrays
# horizontal stack is used to stack arrays horizontally (column-wise).

array([1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
np.column_stack((a,b))  # column stacking of arrays
# column stack is used to stack 1-D arrays as columns into a 2-D array.
# It is similar to hstack but it treats 1-D arrays as columns rather than rows.

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

##### *Splitting Array* #####

In [35]:
c = np.arange(16).reshape(4,4)
c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [36]:
np.hsplit(c,2)

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [43]:
d = np.vsplit(c,2)
d

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [42]:
for i in d:
    print(i)

[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]
