#### *General Questions* ####

In [1]:
import numpy as np

# columns : [Age, Math_Marks, Science_Marks, English_Marks]
data = np.array([
    [15, 85, 90, 80],    # Student 1
    [16, 78, 88, 82],    # Student 2
    [15, 92, 95, 88],    # Student 3
    [17, 80, 85, 78],    # Student 4
    [16, 88, 91, 85]     # Student 5
    ])

In [2]:
#Get the shape of the matrix
data.shape

(5, 4)

In [3]:
# find the average age of students
np.mean(data[:,0])

np.float64(15.8)

In [4]:
# extract math marks of all the students
data[:,1]

array([85, 78, 92, 80, 88])

In [5]:
# find the higest science marks
np.max(data[:,2])

np.int64(95)

In [6]:
# get the details of the student who scored more than 90 marks in maths
data[data[:,1] > 90]

array([[15, 92, 95, 88]])

In [7]:
# increase all students' math marks by 5
data[:,1] += 5
data

array([[15, 90, 90, 80],
       [16, 83, 88, 82],
       [15, 97, 95, 88],
       [17, 85, 85, 78],
       [16, 93, 91, 85]])

In [8]:
# find how many students younger than 16 years are there
len(data[data[:,0] < 16])

2

In [9]:
# calculate the average marks in each subject(column-wise average)
np.mean(data[:,1:], axis=0)

array([89.6, 89.8, 82.6])

In [10]:
# get the data of the student who scored at least 80 in both maths and science
data[(data[:,1] >= 80) & (data[:,2] >= 80)]

array([[15, 90, 90, 80],
       [16, 83, 88, 82],
       [15, 97, 95, 88],
       [17, 85, 85, 78],
       [16, 93, 91, 85]])

In [11]:
# replace all the science marks less than 75 replace with 0
data[data[:,2] < 90, 2] = 0
data

array([[15, 90, 90, 80],
       [16, 83,  0, 82],
       [15, 97, 95, 88],
       [17, 85,  0, 78],
       [16, 93, 91, 85]])